# fly.toml app configuration file generated for roadmr-link-shortener on 2023-07-25T12:05:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "roadmr-link-shortener"
primary_region = "yul"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
