# fly.toml app configuration file generated for roadmr-link-shortener on 2023-07-25T12:05:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "roadmr-link-shortener"
primary_region = "yul"
swap_size_mb = 512


[metrics]
port = 8000
path = "/metrics"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  processes = ["app"]

  [[http_service.checks]]
  grace_period = "10s"
  interval = "1m0s"
  method = "GET"
  path = "/check/healthy"
  timeout = "5s"
  [http_service.concurrency]
  type = "requests"
  hard_limit = 150
  soft_limit = 130
