name: Fly Deploy
on:
  workflow_run:
    workflows: ["Unit tests"]
    branches:
      - main
    types:
      - completed
jobs:
  deploy:
    name: Deploy app
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl version
      - run: flyctl deploy --remote-only --buildkit
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
