name: Unit tests
on:
  push:
    branches:
      - main
  schedule:
    - cron: '25 13,14,15,16,17,18,19,20 * * 1,2,3,4,5'
jobs:
  unit-tests:
    name: Unit tests yes
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: run unit tests
        run: |
          uv run pytest
