name: Unit tests
on:
  push:
    branches:
      - main
jobs:
  unit-tests:
    name: Unit tests yes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install venv
        run: sudo apt-get install python3-virtualenv
      - name: run unit tests
        run: |
          python3 -mvenv venv
          venv/bin/pip install -r requirements-dev.txt
          venv/bin/pytest

